// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/faq/securite.mdx?collection=docs&hash=1753970534178"
import * as docs_5 from "../content/docs/faq/index.mdx?collection=docs&hash=1753970534178"
import * as docs_4 from "../content/docs/faq/fichier-et-gifs.mdx?collection=docs&hash=1753970534178"
import * as docs_3 from "../content/docs/tester-avec-vite.mdx?collection=docs&hash=1753970534178"
import * as docs_2 from "../content/docs/index.mdx?collection=docs&hash=1753970534178"
import * as docs_1 from "../content/docs/environnement-de-developpement.mdx?collection=docs&hash=1753970534178"
import * as docs_0 from "../content/docs/construire-l-application.mdx?collection=docs&hash=1753970534178"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"construire-l-application.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/construire-l-application.mdx"}, data: docs_0 }, { info: {"path":"environnement-de-developpement.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/environnement-de-developpement.mdx"}, data: docs_1 }, { info: {"path":"index.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/index.mdx"}, data: docs_2 }, { info: {"path":"tester-avec-vite.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/tester-avec-vite.mdx"}, data: docs_3 }, { info: {"path":"faq/fichier-et-gifs.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/faq/fichier-et-gifs.mdx"}, data: docs_4 }, { info: {"path":"faq/index.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/faq/index.mdx"}, data: docs_5 }, { info: {"path":"faq/securite.mdx","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/faq/securite.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"/Users/justinregulier/Desktop/Projets/ejda-chat-docs-new/content/docs/meta.json"},"data":{"title":"EJDA Chat","pages":["index","---Support---","faq","---Développeurs---","environnement-de-developpement","tester-avec-vite","construire-l-application"],"description":"Documentation pour EJDA Chat, une application de messagerie sécurisée et collaborative."}}])