name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build
        run: bun run build
      
      - name: Create unique branch name
        id: branch
        run: echo "branch_name=gh-pages-$(date +%s)" >> $GITHUB_OUTPUT
      
      - name: Deploy to GitHub Pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan ${{ steps.branch.outputs.branch_name }}
          git rm -rf .
          cp -r out/* .
          git add .
          git commit -m "Deploy to GitHub Pages - $(date)"
          git push origin ${{ steps.branch.outputs.branch_name }}