name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build
        run: bun run build
      
      - name: Deploy to GitHub Pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create a clean deployment directory
          cd /tmp
          git clone https://github.com/${{ github.repository }}.git deploy-repo
          cd deploy-repo
          
          # Switch to github-pages branch (create if doesn't exist)
          git fetch origin
          if git rev-parse --verify origin/github-pages >/dev/null 2>&1; then
            git checkout github-pages
          else
            git checkout --orphan github-pages
            git rm -rf . 2>/dev/null || true
          fi
          
          # Clear everything and copy only the built files
          rm -rf *
          cp -r ${{ github.workspace }}/out/* .
          
          # Commit and push
          git add .
          git commit -m "Deploy to GitHub Pages - $(date)" || exit 0
          git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git github-pages